# Generated by Django 5.1.6 on 2025-02-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_comments_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
