# Generated by Django 5.1.6 on 2025-02-28 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_notification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='follower',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='following',
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='likes',
            name='post',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]