# Generated by Django 5.1.6 on 2025-03-01 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follower_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follower',
            table='follower',
        ),
    ]
